import type { Metadata } from "next";
import LocalFont from "next/font/local";
import "./globals.css";

const basecoat = LocalFont({
  src: [
    {
      path: "../public/fonts/basecoat-light.ttf",
      style: "normal",
      weight: "400",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={basecoat.className}>{children}</body>
    </html>
  );
}
